const form=document.querySelector("#gigForm"),panel=document.querySelector("#responsePanel"),box=document.querySelector("#responseText"),preview=document.querySelector("#proposalPreview");
const data=()=>Object.fromEntries(new FormData(form).entries());
const date=v=>v?new Date(v+"T12:00:00").toLocaleDateString(undefined,{month:"long",day:"numeric",year:"numeric"}):"";
const time=v=>{if(!v)return"";let [h,m]=v.split(":").map(Number);return new Date(2000,0,1,h,m).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})};
function reply(d){let s=`Hi ${d.firstName||"there"} — thanks for reaching out about live music`;if(d.eventType)s+=` for your ${d.eventType.toLowerCase()}`;if(d.date)s+=` on ${date(d.date)}`;s+=".";if(d.style)s+=` ${d.style} sounds like a good direction.`;if(d.musicians&&d.musicians!=="Not sure yet")s+=` I see you're considering ${d.musicians.toLowerCase()}.`;if(d.needs)s+=` I also saw your note about ${d.needs.trim()}.`;let miss=[];if(!d.date)miss.push("date");if(!d.location)miss.push("location/venue");if(!d.startTime||!d.endTime)miss.push("start and end time");s+=miss.length?` To put the right setup together, I still need the ${miss.join(", ")}.`:" I have the basic event details, so I can put together the right musical setup and a quote.";return s+"\n\nNick Laudani\n617-233-2008"}
function proposal(d){return ["REACHOUT ANSWER — GIG / PROPOSAL SUMMARY","",`Client: ${(d.firstName+" "+d.lastName).trim()||"—"}`,`Email: ${d.email||"—"}`,`Phone: ${d.phone||"—"}`,`Event: ${d.eventType||"—"}`,`Date: ${date(d.date)||"—"}`,`Location: ${d.location||"—"}`,`Start / Finish: ${time(d.startTime)||"—"} – ${time(d.endTime)||"—"}`,`Musicians: ${d.musicians||"—"}`,`Music / style: ${d.style||"—"}`,`Needs: ${d.needs||"—"}`,`Lineup / equipment: ${d.lineup||"—"}`,`Fee: ${d.fee?"$"+d.fee:"NOT SET — Nick decides"}`,`Deposit: ${d.deposit||"NOT SET — Nick decides"}`,"","Status: OWNER REVIEW REQUIRED"].join("\n")}
form.addEventListener("submit",e=>{e.preventDefault();box.value=reply(data());panel.classList.remove("hidden");preview.classList.add("hidden");panel.scrollIntoView({behavior:"smooth"})});
document.querySelector("#copyBtn").onclick=async()=>{await navigator.clipboard.writeText(box.value);document.querySelector("#copyBtn").textContent="Copied"};
document.querySelector("#proposalBtn").onclick=()=>{preview.textContent=proposal(data());preview.classList.remove("hidden")};
form.addEventListener("reset",()=>panel.classList.add("hidden"));
// ReachOut Answer v1 booking-request demo. A real calendar must verify availability before confirmation.
const bookingForm=document.querySelector('#bookingForm');
if(bookingForm){bookingForm.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(bookingForm).entries());const r=document.querySelector('#bookingResult');r.textContent=`Requested: ${d.kind} on ${d.bookDate} at ${d.bookTime} for ${d.length}. This is not confirmed until calendar availability is checked.`;r.classList.remove('hidden');});}
